# Site Info
title: 'del-luna'
#tagline: 
description: 'Undergraduate student'
baseurl: ""
url: https://del-luna.github.io
logo: '/images/avatar.jpg'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Jaeheon Kwon
  description: Undergraduate Dev Blog
  # gravatar: 3c2986ad7ac1f2230ea3596f44563328 # md5 hash of your email address
  contact:
    #linkedin:  https://www.linkedin.com/in/onsemy
    github:    https://github.com/del-luna
    # facebook:  <hide>
    #twitter:   https://twitter.com/onsemy
    # weibo:     http://weibo.com/41173780
    email:    ""

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  #Blog:
  #  - '/blog/'
  Categories:
    - '/blog/categories/'
    - { Ai: '/blog/ai/' }
    #- { Vision: '/blog/vision/' }
    #- { Reinforcement: '/blog/reinforcement/' }
    #- { Recommendation: '/blog/recommendation/' }
    - { Papers: '/blog/papers/' }
    - { PS: '/blog/ps/' }
    #- { C++: '/blog/c++/' }
    #- { Kaggle: '/blog/kaggle/' }
    #- { Mathematics: '/blog/mathematics/' }
    
  #Temp:
  #  - '/blog/temp/'
  #Tags:
  #  - '/blog/tags/'
  About:
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /images/home_1.jpg
  caption: 아카이브용이며 더 이상 업데이트 되지 않습니다. -> https://delluna.notion.site/Blog-022f7f94c2d544a7b8cf5f69c34ce13c

# Plugins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-163332215-1' # leave blank if you don't want google analytics
disqus_short_name: 'jaeheondev' # leave blank if you don't want disqus

